"""
Load drug-drug interaction pairs extracted from FDA label text.
Input: knowledge_base/sources/dataset/interactions_priority_50.csv
       (generated by extract_priority_interactions.py)

Rules:
  - If a pair already has an ANSM entry (severity_ansm IS NOT NULL), keep it — do not downgrade.
  - If a pair has no entry at all, insert with openfda severity and source.
  - severity_active = most conservative of severity_ansm and severity_openfda.
"""

import csv
import os
import psycopg2

conn = psycopg2.connect(
    dbname=os.getenv("POSTGRES_DB", "medflow"),
    user=os.getenv("POSTGRES_USER", "medflow"),
    password=os.getenv("POSTGRES_PASSWORD", "medflow"),
    host=os.getenv("POSTGRES_HOST", "localhost"),
)
cur = conn.cursor()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "../sources/dataset/interactions_priority_50.csv")

SEVERITY_RANK = {
    "contre_indique":    4,
    "deconseillee":      3,
    "precaution_emploi": 2,
    "a_prendre_en_compte": 1,
    "major":             4,
    "moderate":          2,
    "minor":             1,
}

def most_conservative(s1, s2):
    if not s1:
        return s2
    if not s2:
        return s1
    return s1 if SEVERITY_RANK.get(s1, 0) >= SEVERITY_RANK.get(s2, 0) else s2


def get_molecule_id(inn: str):
    cur.execute("SELECT id FROM molecules WHERE inn = %s", (inn,))
    row = cur.fetchone()
    return row[0] if row else None


loaded, skipped_no_mol, skipped_exists, updated = 0, 0, 0, 0

with open(CSV_PATH, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        inn_a = row["inn_a"].strip()
        inn_b = row["inn_b"].strip()
        severity_openfda = row["severity_inferred"].strip()
        extracted_text   = row["extracted_text"].strip()[:1000]

        id_a = get_molecule_id(inn_a)
        id_b = get_molecule_id(inn_b)

        if not id_a or not id_b:
            skipped_no_mol += 1
            continue

        # Always store in consistent (smaller id first) order
        if id_a > id_b:
            id_a, id_b = id_b, id_a

        # Check if a row already exists
        # Note: schema uses severity_drugbank for non-ANSM severity sources
        cur.execute("""
            SELECT id, severity_ansm, severity_drugbank
            FROM drug_interactions
            WHERE molecule_a_id = %s AND molecule_b_id = %s
        """, (id_a, id_b))
        existing = cur.fetchone()

        if existing:
            existing_id, existing_ansm, existing_drugbank = existing
            # Only update if this row has no non-ANSM severity yet
            if existing_drugbank:
                skipped_exists += 1
                continue
            # Add openfda severity to existing row; recompute severity_active
            new_active = most_conservative(existing_ansm, severity_openfda)
            cur.execute("""
                UPDATE drug_interactions
                SET severity_drugbank = %s,
                    severity_active   = %s,
                    clinical_effect   = COALESCE(clinical_effect, %s)
                WHERE id = %s
            """, (severity_openfda, new_active, extracted_text, existing_id))
            updated += 1
        else:
            try:
                cur.execute("SAVEPOINT sp")
                cur.execute("""
                    INSERT INTO drug_interactions
                        (molecule_a_id, molecule_b_id,
                         severity_drugbank, severity_active,
                         clinical_effect, source_confidence)
                    VALUES (%s, %s, %s, %s, %s, %s)
                """, (id_a, id_b, severity_openfda, severity_openfda,
                      extracted_text, "openfda_label"))
                cur.execute("RELEASE SAVEPOINT sp")
                loaded += 1
            except Exception as e:
                cur.execute("ROLLBACK TO SAVEPOINT sp")
                print(f"  SKIP {inn_a}+{inn_b}: {e}")
                skipped_no_mol += 1

conn.commit()

cur.execute("SELECT COUNT(*) FROM drug_interactions")
total = cur.fetchone()[0]

cur.close()
conn.close()

print(f"\nDone.")
print(f"  New pairs inserted:       {loaded}")
print(f"  Existing pairs enriched:  {updated}")
print(f"  Already had openfda data: {skipped_exists}")
print(f"  Skipped (no molecule):    {skipped_no_mol}")
print(f"  Total drug_interactions:  {total}")
