"""
Load CYP enzyme relationships from the scraped Flockhart P450 table.

Source: knowledge_base/sources/dataset/flockhart_cyp_table.csv
        generated by knowledge_base/loaders/scrape_flockhart.py

The Flockhart table (Indiana University) is the authoritative clinical reference
for CYP substrate/inhibitor/inducer classifications with strength grading.

Name normalization:
  Some Flockhart drug names differ from our INN standard — mapped below.
  Drugs not in the CSV (non-CYP-metabolized) are silently skipped.
"""

import csv
import os
import psycopg2

conn = psycopg2.connect(
    dbname=os.getenv("POSTGRES_DB", "medflow"),
    user=os.getenv("POSTGRES_USER", "medflow"),
    password=os.getenv("POSTGRES_PASSWORD", "medflow"),
    host=os.getenv("POSTGRES_HOST", "localhost"),
)
cur = conn.cursor()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(BASE_DIR, "../sources/dataset/flockhart_cyp_table.csv")

# Flockhart name → canonical INN stored in molecules table
FLOCKHART_TO_INN = {
    "s-warfarin":           "warfarin",
    "r-warfarin":           "warfarin",
    "rifampin":             "rifampicin",
    "valproic acid":        "valproate",
    "glyburide/glibenclamide": "glibenclamide",
    "gleevec":              "imatinib",   # brand name duplicate of imatinib
}


def resolve_inn(flockhart_name: str) -> str:
    return FLOCKHART_TO_INN.get(flockhart_name, flockhart_name)


# Clear existing CYP data so we start clean from the Flockhart source
cur.execute("DELETE FROM cyp_relationships")
print("Cleared existing cyp_relationships rows.")

loaded, skipped_no_mol, skipped_other = 0, 0, 0

with open(CSV_PATH, newline="", encoding="utf-8") as f:
    for row in csv.DictReader(f):
        flockhart_drug = row["drug"].strip()
        inn = resolve_inn(flockhart_drug)
        enzyme = row["enzyme"].strip()
        relationship = row["relationship"].strip()
        strength = row["strength"].strip() or None

        cur.execute("SELECT id FROM molecules WHERE inn = %s", (inn,))
        mol = cur.fetchone()
        if not mol:
            skipped_no_mol += 1
            continue

        try:
            cur.execute("SAVEPOINT cyp_sp")
            cur.execute("""
                INSERT INTO cyp_relationships (molecule_id, enzyme, relationship, strength)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (molecule_id, enzyme, relationship) DO UPDATE SET
                    strength = EXCLUDED.strength
            """, (mol[0], enzyme, relationship, strength))
            cur.execute("RELEASE SAVEPOINT cyp_sp")
            loaded += 1
        except Exception as e:
            cur.execute("ROLLBACK TO SAVEPOINT cyp_sp")
            print(f"  SKIP {inn} {enzyme} {relationship}: {e}")
            skipped_other += 1

# ── Supplements: entries not in Flockhart but well-established in literature ──
# Flockhart does not classify every drug as inhibitor/inducer even when evidence
# exists. These are sourced from FDA Drug Interactions Table and primary literature.
SUPPLEMENTS = [
    # valproate: weak inhibitor of CYP2C9 and CYP2C19 (FDA label, multiple studies)
    ("valproate",        "CYP2C9",  "INHIBITOR", "weak"),
    ("valproate",        "CYP2C19", "INHIBITOR", "weak"),
    # isoniazid: strong CYP2E1 inhibitor, weak CYP3A4 inhibitor
    ("isoniazid",        "CYP2E1",  "INHIBITOR", "strong"),
    ("isoniazid",        "CYP3A4",  "INHIBITOR", "weak"),
    # allopurinol: weak CYP2C9 inhibitor (warfarin interaction via this pathway)
    ("allopurinol",      "CYP2C9",  "INHIBITOR", "weak"),
    # ethinylestradiol: CYP3A4 substrate (Flockhart lists estradiol, not EE specifically)
    ("ethinylestradiol", "CYP3A4",  "SUBSTRATE", None),
    # metronidazole: moderate CYP2C9 inhibitor (warfarin interaction, well established)
    ("metronidazole",    "CYP2C9",  "INHIBITOR", "moderate"),
]

# ── Strength overrides: Flockhart rating differs from FDA/ANSM clinical guidance ──
# Applied after the main load to correct known conservative underclassifications.
STRENGTH_OVERRIDES = [
    # Fluconazole CYP2C9: Flockhart = moderate; FDA Drug Interaction Guidance = strong.
    # ANSM Thesaurus confirms strong — the warfarin+fluconazole contre_indique rating
    # is based precisely on this strong inhibition. Moderate would understate the risk.
    ("fluconazole", "CYP2C9", "INHIBITOR", "strong"),
]

for (inn, enzyme, relationship, strength) in SUPPLEMENTS:
    cur.execute("SELECT id FROM molecules WHERE inn = %s", (inn,))
    mol = cur.fetchone()
    if not mol:
        continue
    try:
        cur.execute("SAVEPOINT sup_sp")
        cur.execute("""
            INSERT INTO cyp_relationships (molecule_id, enzyme, relationship, strength)
            VALUES (%s, %s, %s, %s)
            ON CONFLICT (molecule_id, enzyme, relationship) DO UPDATE SET
                strength = EXCLUDED.strength
        """, (mol[0], enzyme, relationship, strength))
        cur.execute("RELEASE SAVEPOINT sup_sp")
        loaded += 1
    except Exception as e:
        cur.execute("ROLLBACK TO SAVEPOINT sup_sp")
        print(f"  SKIP supplement {inn} {enzyme} {relationship}: {e}")

for (inn, enzyme, relationship, strength) in STRENGTH_OVERRIDES:
    cur.execute("SELECT id FROM molecules WHERE inn = %s", (inn,))
    mol = cur.fetchone()
    if not mol:
        continue
    cur.execute("""
        UPDATE cyp_relationships SET strength = %s
        WHERE molecule_id = %s AND enzyme = %s AND relationship = %s
    """, (strength, mol[0], enzyme, relationship))
    if cur.rowcount:
        print(f"  OVERRIDE  {inn} {enzyme} {relationship} -> {strength}")

conn.commit()

cur.execute("SELECT COUNT(*) FROM cyp_relationships")
total = cur.fetchone()[0]

cur.execute("""
    SELECT r.relationship, COUNT(*)
    FROM cyp_relationships r
    GROUP BY r.relationship
    ORDER BY r.relationship
""")
by_rel = cur.fetchall()

cur.close()
conn.close()

print(f"\nDone.")
print(f"  Loaded:                {loaded}")
print(f"  Skipped (no molecule): {skipped_no_mol}")
print(f"  Skipped (other):       {skipped_other}")
print(f"  Total in DB:           {total}")
print(f"  By relationship:       {dict(by_rel)}")
